spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_show_dev?createDatabaseIfNotExist=true
    username: root
    password: root0000

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

jwt:
  secret: V0du1Y2rYkt3LWwaq7c/HNiLP8kz3L9dGsm3id53LII=